version: "3.9"

services:
  api:
    build:
      context: ./ServidorAPI
    image: proyecto_comecat-api
    container_name: api
    ports:
      - "5007:8080"  # HTTP
      - "5008:8081"  # HTTPS fijo
    networks:
      - red_gatos
    volumes:
      - api_data:/app/data
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  db:
    build:
      context: ./ServidorBBDD
    image: proyecto_comecat-db
    container_name: db
    ports:
      - "5009:8080"   # HTTP DB
      - "5010:8081"   # HTTPS DB
    networks:
      - red_gatos
    volumes:
      - datos_db:/db

  blazor:
    build:
      context: ./ServidorBlazor
    image: proyecto_comecat-blazor
    container_name: blazor
    ports:
      - "5011:5002"  # HTTP Blazor
    networks:
      - red_gatos
    volumes:
      - blazor_data:/app/data

  mqtt:
    build:
      context: ./ServidorMQTT
    image: proyecto_comecat-mqtt
    container_name: mqtt
    ports:
      - "5012:1883"   # MQTT
    networks:
      - red_gatos
    volumes:
      - mqtt_config:/mosquitto/config
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log

  servidorprueba:
    build:
      context: ./ServidorPrueba
    image: proyecto_comecat-prueba
    container_name: servidor_prueba
    depends_on:
      - api
    networks:
      - red_gatos
    ports:
      - "5013:5004"  # Pruebas
    volumes:
      - pruebas_data:/tests

  servidorn8n:
    build:
      context: ./ServidorN8N
      dockerfile: Dockerfile
    image: proyecto_comecat-n8n
    container_name: servidor_n8n
    ports:
      - "5014:5678"   # n8n accesible en puerto consecutivo
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_USER_MANAGEMENT_DISABLED=true   # permite login solo con usuario/contraseña
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - red_gatos
    depends_on:
      - api
      - mqtt
      - db

volumes:
  api_data:
  datos_db:
  blazor_data:
  mqtt_config:
  mqtt_data:
  mqtt_log:
  pruebas_data:
  n8n_data:

networks:
  red_gatos:
    driver: bridge
